# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net


name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- '*'

pr:
- '*'

pool:
  vmImage: 'VS2017-Win2016'
  demands:
  - 'msbuild'
  - 'visualstudio'

variables:
  solution: '**/*.sln'

strategy:
  matrix:
    debug-x86:
      buildPlatform: 'x86'
      buildConfiguration: 'Debug'
    debug-x64:
      buildPlatform: 'x64'
      buildConfiguration: 'Debug'
    release-x86:
      buildPlatform: 'x86'
      buildConfiguration: 'Release'
    release-x64:
      buildPlatform: 'x64'
      buildConfiguration: 'Release'

steps:
- checkout: 'self'
  lfs: true
  submodules: 'recursive'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: '4.4.1'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'
    verbosityRestore: 'Normal'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    vsVersion: '15.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'